"""empty message

Revision ID: 181486d3349
Revises: 2f7c1b4e33c
Create Date: 2015-07-05 20:03:03.541393

"""

# revision identifiers, used by Alembic.
revision = '181486d3349'
down_revision = '2f7c1b4e33c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
