"""empty message

Revision ID: 2f7c1b4e33c
Revises: 4ea72a17a3f
Create Date: 2015-07-05 18:24:15.005712

"""

# revision identifiers, used by Alembic.
revision = '2f7c1b4e33c'
down_revision = '4ea72a17a3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('time', sa.String(length=300), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=300), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('time', sa.String(length=300), nullable=True),
    sa.Column('num_err', sa.Integer(), nullable=True),
    sa.Column('err_desc', sa.String(), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('response_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    op.drop_table('assignment')
    ### end Alembic commands ###
